server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: order-service
  lifecycle:
      timeout-per-shutdown-phase: 15s
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/polardb_order
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-migration-naming: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order
